//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1dv402_oklib08_1_3_godtycklig_lonerevision {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1dv402_oklib08_1_3_godtycklig_lonerevision.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medellön:.
        /// </summary>
        internal static string Average_Result {
            get {
                return ResourceManager.GetString("Average_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godtycklig lönerevision - nivå C.
        /// </summary>
        internal static string Console_Title {
            get {
                return ResourceManager.GetString("Console_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck valfri tangent för att fortsätta eller avsluta med Esc.
        /// </summary>
        internal static string Continue_Prompt {
            get {
                return ResourceManager.GetString("Continue_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lönespridning:.
        /// </summary>
        internal static string Dispersion_Result {
            get {
                return ResourceManager.GetString("Dispersion_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lönen du har angett är för låg, lönen måste vara minst 10 000:-! Försök igen!.
        /// </summary>
        internal static string Error_Higher_Salary {
            get {
                return ResourceManager.GetString("Error_Higher_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste mata in minst två löner för att kunna göra en beräkning!.
        /// </summary>
        internal static string Error_More_Than_Two_Message {
            get {
                return ResourceManager.GetString("Error_More_Than_Two_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felaktig inmatning, ange antal löner att mata in: .
        /// </summary>
        internal static string Error_Not_A_Number_Message {
            get {
                return ResourceManager.GetString("Error_Not_A_Number_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------.
        /// </summary>
        internal static string Line_Result {
            get {
                return ResourceManager.GetString("Line_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medianlön:.
        /// </summary>
        internal static string Median_Result {
            get {
                return ResourceManager.GetString("Median_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange antal löner att mata in: .
        /// </summary>
        internal static string Number_Of_Salary_Prompt {
            get {
                return ResourceManager.GetString("Number_Of_Salary_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ange lön nummer .
        /// </summary>
        internal static string Salary_Prompt {
            get {
                return ResourceManager.GetString("Salary_Prompt", resourceCulture);
            }
        }
    }
}
